services:
  postgres:
    image: postgres:14 # Using PostgreSQL 14 for better stability
    container_name: sundayschool_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sundayschool
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command: postgres -c listen_addresses='*'

volumes:
  postgres_data: # Defines a named volume for data persistence
